name: Build .NET Framework Application

on:
  push:
    paths:
      - ".code/ChmlFrp_WPF_Clienter/**"
      - ".github/workflows/Build.yml"
  pull_request:
    paths:
      - ".code/ChmlFrp_WPF_Clienter/**"
      - ".github/workflows/Build.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release] #,Debug

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Describe & Version
        shell: bash
        run: |
          describe=`git describe --tags --always`
          version=$(grep 'AssemblyVersion("' ".code/ChmlFrp_WPF_Clienter/Properties/AssemblyInfo.cs" | sed -E 's/.*AssemblyVersion\("([^"]+)".*/\1/')
          echo "describe=$describe" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild ".code\\ChmlFrp_WPF_Clienter.sln" -p:Configuration=${{ matrix.configuration }}

      - name: Move Executable to Root
        run: |
          Move-Item -Path .code\ChmlFrp_WPF_Clienter\bin\${{ matrix.configuration }}\ChmlFrp_WPF_Clienter.exe -Destination .\

      - name: Upload a Build Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}-Pre-alpha${{ env.describe }}-${{ env.version }}-Windows
          path: |
            ChmlFrp_WPF_Clienter.exe
            README.md
            LICENSE.md

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lanzou-api

      - name: Upload to LanZouCloud
        env:
          LANZOUCLOUD_USERNAME: ${{ secrets.WEBDAV_USERNAM }}
          LANZOUCLOUD_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        run: |
          python -c "
          from lanzou.api import LanZouCloud
          lzy = LanZouCloud()
          lzy.login('${{ env.LANZOUCLOUD_USERNAME }}', '${{ env.LANZOUCLOUD_PASSWORD }}')
          lzy.upload_file('D:\a\ChmlFrp_WPF_Clienter\ChmlFrp_WPF_Clienter\.code\ChmlFrp_WPF_Clienter\bin\Release\ChmlFrp_WPF_Clienter.exe', folder_id=-1)
          lzy.logout()
          "
          
